package com.typesafe.conductr.clientlib.scala.models

import java.util.UUID

/**
 * HTTP result for one of the following bundle requests:
 * - Loading a bundle
 * - Scaling (running) a bundle
 * - Stopping a bundle
 * - Unloading a bundle
 */
sealed trait BundleRequestResult

/**
 * Represents a HTTP success result for a bundle request
 * @param requestId The unique request id generated by the ConductR control server
 * @param bundleId The given bundle id of the request
 */
final case class BundleRequestSuccess(requestId: UUID, bundleId: BundleId) extends BundleRequestResult

/**
 * Represents a HTTP failure result for a bundle request
 * @param code The HTTP status code
 * @param error The error message
 */
final case class BundleRequestFailure(code: Int, error: String) extends HttpFailure with BundleRequestResult